# https://docs.travis-ci.com/user/languages/java/
# https://docs.travis-ci.com/user/reference/osx/
os: linux
dist: xenial
language: java

addons:
  apt:  # only active on Linux
    packages:
      - ant
  hostname: jyshort
  homebrew:  # only active on macOS
    update: true
    packages:
      - ant

jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  
jobs:
  include:
    - os: osx
      osx_image: xcode9.3  # Last supporting Java 8
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode11.5
      jdk: openjdk14
    - language: python  # lint Python code for syntax errors and undefined names
      install: pip install --upgrade pip
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  allow_failures:
    - language: python

install: ant developer-build
script: ant regrtest-travis

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net
