# https://docs.travis-ci.com/user/languages/java/
# https://docs.travis-ci.com/user/reference/osx/
# https://docs.travis-ci.com/user/reference/windows/
os: linux
dist: focal
language: java

addons:
  apt:  # only active on Linux
    packages:
      - ant
  hostname: jyshort
  homebrew:  # only active on macOS
    update: true
    packages:
      - ant

services: xvfb

jdk:
  # - openjdk12
  # - openjdk14
  
jobs:
  include:
    #- name: "openjdk8 on Linux"
    #  jdk: openjdk8
    #- name: "openjdk11 on Linux"
    #  jdk: openjdk11
    #- name: "openjdk13 on Linux"
    #  jdk: openjdk13
    #- name: "openjdk8 on macOS"
    #  os: osx
    #  osx_image: xcode9.3  # Last supporting Java 8
    #  jdk: oraclejdk8
    #- name: "openjdk13 on macOS"
    #  os: osx
    #  osx_image: xcode11.5
    #  jdk: openjdk13
    - name: "openjdk13 on Windows"
      os: windows
      language: shell  # Travis CI Windows does not yet support language: java
      env:
        - PATH="/c/Program Files/AdoptOpenJDK/jdk-13.0.2.8-hotspot/bin:/c/ProgramData/chocolatey/bin:$PATH"
        - JAVA_HOME="/c/Program Files/AdoptOpenJDK/jdk-13.0.2.8-hotspot/bin:$JAVA_HOME"
        - ANT_HOME=$(pwd)
      before_install:
        - echo $PATH || true
        - ant -version || true
        - powershell choco install adoptopenjdk13
        - ls "/c/ProgramFiles/AdoptOpenJDK/jdk-13.0.2.8-hotspot/bin" || true
        - ls "/c/Program Files/AdoptOpenJDK/jdk-13.0.2.8-hotspot/bin"
        - powershell refreshenv || true
        - java -version || true
        - javac -version || true
        - curl -H https://downloads.apache.org/ant/binaries/apache-ant-1.10.8-bin.zip | unzip
        - ls
        - ./bin/ant -version || true
        - ant -version || true
        # - powershell choco install ant
        # - powershell refreshenv || true
        - ant -version || true
        # - cat C:\ProgramData\chocolatey\logs\chocolatey.log
    #- name: "Lint Python 2 code for syntax errors and undefined names"
    #  language: python  # lint Python code for syntax errors and undefined names
    #  python: 2.7
    #  install: pip install flake8
    #  script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #- name: "Lint Python 3 code for syntax errors and undefined names"
    #  language: python  # lint Python code for syntax errors and undefined names
    #  install: pip install flake8
    #  script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  allow_failures:
    - language: python
    - jdk: openjdk12  # fails on: test_dunder_init (test.test_import_jy.MislabeledImportTestCase)
                      # ..and on: test_import_star (test.test_import_jy.ImpTestCase)
    - jdk: openjdk14  # hangs on: [exec] test_subprocess

install: ant developer-build
script: ant regrtest-travis

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net
